# Generated by Django 3.0.8 on 2020-08-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_request',
            name='company',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], default=2, max_length=30),
        ),
        migrations.AlterField(
            model_name='funding_request',
            name='stage',
            field=models.CharField(choices=[(1, 'Idea'), (2, 'Concept'), (3, 'Established')], default=1, max_length=30),
        ),
    ]
