# Generated by Django 3.0.8 on 2020-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200807_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_request',
            name='company',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=2, max_length=30),
        ),
        migrations.AlterField(
            model_name='funding_request',
            name='stage',
            field=models.CharField(choices=[('Idea', 'Idea'), ('Concept', 'Concept'), ('Established', 'Established')], default=1, max_length=30),
        ),
    ]
